# Site settings
baseurl = "https://paramjot.io/"
#baseurl = "https://pchhina.github.io/portfolioSite/"
languageCode = "en-us"
title = "Paramjot Singh"
theme = ""
paginate = 5
#relativeURLs = true
staticDir = ["static"]

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Mr. Hugo"
    description = "My awesome description"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "param.chhina@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "paramjot singh"
    
    [taxonomies]
        tag = "tags"
        category = "categories"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "param2.jpg"
        name = "Hi! I am Paramjot Singh"
        subtitle = "I am a mechanical engineer interested in using open source tools to derive meaning from data."


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        
        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"

    [params.blog]
        title = "From the Blog" 
        navtitle = "Blog" 
        summary_length = 300

        [params.blog.button]
            text = "All Posts"
            link = "post/"
            icon = "download"      



    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I work at [Gamma Technologies](https://www.gtisoft.com/) where I help engineers at **Ferrari, BMW, Ford, US Air Force** and many others design better vehicles. I do that through developing and supporting GT-SUITE, a powerful system-level simulation software, that allows our customers to evaluate their design ideas accurately before making any test prototypes. Please see my [linkedin](https://www.linkedin.com/in/paramjot-singh-569959139/) account if you are interested in learning more about this area of my work."
        right = "In my spare time, I learn and try to build things using open source tools. The powerful nature of these tools and the awesome community building them has kept my curiosity growing to understand data in useful and meaningful ways. All my work on this website is open source and available on [Github] (https://github.com/pchhina). Please feel free to look through my projects. I would appreciate any critique and feedback."

        [params.about.button]
            text = "Download them"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["2675 Asbury Dr", "Aurora, IL 60504"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "https://github.com/pchhina"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "https://www.linkedin.com/in/paramjot-singh-569959139"


        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
